version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: my_mysql_server
    depends_on:
      - nginx

volumes:
  mysql_data: