version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - product-service
    networks:
      - app-network

  # product Service
  product-service:
    build: ./product-service
    ports:
      - "3006:3006"
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/userdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
      
      
  order-service:
    build: ./order-service
    ports:
      - "3007:3007"
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/userdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network


volumes:
  mongo_data:

networks:
  app-network: